### PR TITLE
Use time_select and date_select to get 24 hour format.

### LINKED ISSUE #235: As a German, I always want to use the standard timepicker with military time format in the lecture settings.
DEP: None
AC:
- [ ] No matter in which environment, the time picker of the lecture settings always uses military time (24h)

### PR DESCRIPTION
**Pull request by WorldofJARcraft**
# Resolves #235

I had to switch to time_select field because time_field did not work properly in Chrome. Now it looks like this:

image

### CODE REVIEW

**Comment by adrianjost** [comment]
I would consider this solution as a bad UX but we need to discuss with Alex
 You just solved the issue. I will talk to him soon and will post updates here. :)

**Comment by adrianjost** [comment]
I would consider this solution as a bad UX but we need to discuss with Alex
 You just solved the issue. I will talk to him soon and will post updates here. :)

**Comment by WorldofJARcraft** [comment]
Already asked.  
time_field does not work properly, and none of the jquery/bootstrap date picker gems worked, so I do not see any other option...

**Comment by adrianjost** [comment]
Yes but should we fix something like this issue at all? We clearly disrespect the users preferred settings with this change and as we learned we shouldn't work against the system ;D

**Comment by WorldofJARcraft** [comment]
Actually, some Browsers always show time fields with AM and PM, no matter how the user set the locales. HTML time inputs are just broken...

**Comment by WorldofJARcraft** [comment]
@Blatzheim s decision.

**Comment by adrianjost** [comment]
> Actually, some Browsers (Opera) always seem to show time fields with AM and PM, no matter how the user set the locales.

I can not confirm this. Maybe they are using some unknown heuristic. 

For me it behaves like documented here and I see the 24h format in all mayor browsers: (haven't tested safari)
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time#Appearance
image

**Comment by adrianjost** [comment]
I haven't found great poylfills so this is the best option that works on all systems. Even if the UX isn't great.
https://github.com/hpi-swt2/lecture-portal/pull/315

**Pull request merged**
