### PR TITLE
Feature/#45 edit lectures

### LINKED ISSUE #45: As a lecturer, I can edit the lectures settings (e.g. Title, Summary etc.) before and after i have started it (Estimation 3)
- A lecture that has not been started has the button "edit" next to it in the ["My lectures" list ](https://www.figma.com/proto/78SUuNyEDnrKGGeJPmvnmp/Paper-Prototype-%231?node-id=32%3A14&scaling=min-zoom)

- Clicking on "Edit" next to the lecture in the "My lectures" list will present the user with a separate edit view (tbd), from which he can only go back to the "My lectures" list

- Once a lecture is running, switching to the ["Settings" Tab](https://www.figma.com/proto/78SUuNyEDnrKGGeJPmvnmp/Paper-Prototype-%231?node-id=20%3A89&scaling=min-zoom) will present and provide the option to change Title, Description and wether the lecturer wants to include Questions and/or polls for this lecture

_Hint:
Use the [current paper prototype](https://www.figma.com/file/78SUuNyEDnrKGGeJPmvnmp/Paper-Prototype-1?node-id=0%3A1) as guidance, but remember that there will be a new version with a dashboard by wednesday._

### PR DESCRIPTION
**Pull request by WorldofJARcraft**
# Resolves #45.
This PR adds the feature of editing settings of a lecture while it is active.

Acceptance Criteria:
- [x] A lecture that has not been started has the button "edit" next to it in the "My lectures" list

- [x] Clicking on "Edit" next to the lecture in the "My lectures" list will present the user with a separate edit view (tbd), from which he can only go back to the "My lectures" list

- [x] Once a lecture is running, switching to the "Settings" Tab will present and provide the option to change Title, Description and wether the lecturer wants to include Questions and/or polls for this lecture

Testing steps:
See Acceptance criteria.

Steps needed for migration:
- None.

---

Definition Of Done:
- [ ] [Class-Diagram](https://www.lucidchart.com/invitations/accept/705a122b-58a9-4dfa-8b16-c936bc0a46bc) updated --> no changes, only edited views and tests

### CODE REVIEW

**Comment by MartinBuessemeyer** [comment]
> from which he can only go back to the "My lectures" list

Sorry but that particular point does not work does not work. Can you fix this?
I guess this needs to be changed in the _lecture controller_ in the _method update_ since it is forwarding the client. Maybe just replacing the redirect is enough.

**Comment by MartinBuessemeyer** [comment]
In order to fix the problem mentioned from @adrianjost you should to look at the views/lectures/show.html.erb.

**Comment by adrianjost** [comment]
@MartinBuessemeyer @WorldofJARcraft I fixed all the issues mentioned in the review. Please review again.

**Comment by adrianjost** [comment]
depends on #126

**Pull request merged**
